secrets:
  redis-connection:
    name: redis-connection
    labels:
      app: stagetime-server
    dataType: data
    secretKVs:
      REDIS_SERVER: MTAuMzEuMTAzLjE2MQo=
      REDIS_PORT: MzE1MzEK
      REDIS_PASSWORD: d2Vhaw==

customresources:
  stagetime-ingress-certificate:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: stagetime-server-ingress
      labels:
        app: stagetime-server
    spec:
      commonName: stagetime.app.sthings.tiab.ssc.sva.de
      dnsNames:
        - stagetime.app.sthings.tiab.ssc.sva.de
      issuerRef:
        name: cluster-issuer-approle
        kind: ClusterIssuer
      secretName: stagetime-server-ingress-tls

ingress:
  stagetime-server:
    labels:
      app: stagetime-server
    name: stagetime-server
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    service:
      name: stagetime-server-service
      port: 80
      path: /
      pathType: Prefix
    hostname: stagetime
    domain: dev21.sthings-vsphere.labul.sva.de
    tls:
      secretName: stagetime-server-ingress-tls
      host: stagetime.dev21.sthings-vsphere.labul.sva.de
