---
releases:
  - name: redis-stack
    installed: true
    namespace: stagetime-redis
    chart: redis/redis
    version: 17.1.4
    values:
      - "env/redis-stack.yaml.gotmpl"
  - name: stagetime-server
    installed: true
    namespace: stagetime
    chart: stagetime-server/stagetime-server
    version: v0.4.44
    values:
      - "env/values.yaml.gotmpl"
environments:
  labul-pve-dev:
    values:
      - env/defaults.yaml
      - env/{{ .Environment.Name }}.yaml
  vcluster:
    values:
      - env/defaults.yaml
      - env/{{ .Environment.Name }}.yaml
repositories:
  - name: stagetime-server
    url: scr.cd43.sthings-pve.labul.sva.de/stagetime-server
    oci: true
  - name: redis
    url: https://charts.bitnami.com/bitnami
helmDefaults:
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: true
