// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: revisionrun/response.proto

package yacht_application_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_Result int32

const (
	Response_SUCCESS Response_Result = 0
	Response_ERROR   Response_Result = 1
)

// Enum value maps for Response_Result.
var (
	Response_Result_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	Response_Result_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x Response_Result) Enum() *Response_Result {
	p := new(Response_Result)
	*p = x
	return p
}

func (x Response_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_revisionrun_response_proto_enumTypes[0].Descriptor()
}

func (Response_Result) Type() protoreflect.EnumType {
	return &file_revisionrun_response_proto_enumTypes[0]
}

func (x Response_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Result.Descriptor instead.
func (Response_Result) EnumDescriptor() ([]byte, []int) {
	return file_revisionrun_response_proto_rawDescGZIP(), []int{0, 0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  Response_Result   `protobuf:"varint,1,opt,name=result,proto3,enum=revisionrun.Response_Result" json:"result,omitempty"`
	Success *Response_Success `protobuf:"bytes,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   *Response_Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_revisionrun_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_revisionrun_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_revisionrun_response_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetResult() Response_Result {
	if x != nil {
		return x.Result
	}
	return Response_SUCCESS
}

func (x *Response) GetSuccess() *Response_Success {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *Response) GetError() *Response_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Response_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Response_Success) Reset() {
	*x = Response_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_revisionrun_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Success) ProtoMessage() {}

func (x *Response_Success) ProtoReflect() protoreflect.Message {
	mi := &file_revisionrun_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Success.ProtoReflect.Descriptor instead.
func (*Response_Success) Descriptor() ([]byte, []int) {
	return file_revisionrun_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Response_Success) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors  []byte `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
}

func (x *Response_Error) Reset() {
	*x = Response_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_revisionrun_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Error) ProtoMessage() {}

func (x *Response_Error) ProtoReflect() protoreflect.Message {
	mi := &file_revisionrun_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Error.ProtoReflect.Descriptor instead.
func (*Response_Error) Descriptor() ([]byte, []int) {
	return file_revisionrun_response_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Response_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response_Error) GetErrors() []byte {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_revisionrun_response_proto protoreflect.FileDescriptor

var file_revisionrun_response_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x75, 0x6e, 0x2f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x75, 0x6e, 0x22, 0xa8, 0x02, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x72, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x72, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x72,
	0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x1d, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x39, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x42, 0x44, 0x5a, 0x42, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x75, 0x62, 0x2e,
	0x73, 0x76, 0x61, 0x2e, 0x64, 0x65, 0x2f, 0x4c, 0x61, 0x62, 0x2f, 0x73, 0x74, 0x75, 0x74, 0x74,
	0x67, 0x61, 0x72, 0x74, 0x2d, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x79, 0x61, 0x63, 0x68,
	0x74, 0x2f, 0x79, 0x61, 0x63, 0x68, 0x74, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_revisionrun_response_proto_rawDescOnce sync.Once
	file_revisionrun_response_proto_rawDescData = file_revisionrun_response_proto_rawDesc
)

func file_revisionrun_response_proto_rawDescGZIP() []byte {
	file_revisionrun_response_proto_rawDescOnce.Do(func() {
		file_revisionrun_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_revisionrun_response_proto_rawDescData)
	})
	return file_revisionrun_response_proto_rawDescData
}

var file_revisionrun_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_revisionrun_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_revisionrun_response_proto_goTypes = []interface{}{
	(Response_Result)(0),     // 0: revisionrun.Response.Result
	(*Response)(nil),         // 1: revisionrun.Response
	(*Response_Success)(nil), // 2: revisionrun.Response.Success
	(*Response_Error)(nil),   // 3: revisionrun.Response.Error
}
var file_revisionrun_response_proto_depIdxs = []int32{
	0, // 0: revisionrun.Response.result:type_name -> revisionrun.Response.Result
	2, // 1: revisionrun.Response.success:type_name -> revisionrun.Response.Success
	3, // 2: revisionrun.Response.error:type_name -> revisionrun.Response.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_revisionrun_response_proto_init() }
func file_revisionrun_response_proto_init() {
	if File_revisionrun_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_revisionrun_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_revisionrun_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_revisionrun_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_revisionrun_response_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_revisionrun_response_proto_goTypes,
		DependencyIndexes: file_revisionrun_response_proto_depIdxs,
		EnumInfos:         file_revisionrun_response_proto_enumTypes,
		MessageInfos:      file_revisionrun_response_proto_msgTypes,
	}.Build()
	File_revisionrun_response_proto = out.File
	file_revisionrun_response_proto_rawDesc = nil
	file_revisionrun_response_proto_goTypes = nil
	file_revisionrun_response_proto_depIdxs = nil
}
