// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: revisionrun/service.proto

package sweatShop_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SweatShopApplicationServiceClient is the client API for SweatShopApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SweatShopApplicationServiceClient interface {
	CreateRevisionRun(ctx context.Context, in *CreateRevisionRunRequest, opts ...grpc.CallOption) (*Response, error)
}

type sweatShopApplicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSweatShopApplicationServiceClient(cc grpc.ClientConnInterface) SweatShopApplicationServiceClient {
	return &sweatShopApplicationServiceClient{cc}
}

func (c *sweatShopApplicationServiceClient) CreateRevisionRun(ctx context.Context, in *CreateRevisionRunRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/revisionrun.SweatShopApplicationService/CreateRevisionRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SweatShopApplicationServiceServer is the server API for SweatShopApplicationService service.
// All implementations must embed UnimplementedSweatShopApplicationServiceServer
// for forward compatibility
type SweatShopApplicationServiceServer interface {
	CreateRevisionRun(context.Context, *CreateRevisionRunRequest) (*Response, error)
	mustEmbedUnimplementedSweatShopApplicationServiceServer()
}

// UnimplementedSweatShopApplicationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSweatShopApplicationServiceServer struct {
}

func (UnimplementedSweatShopApplicationServiceServer) CreateRevisionRun(context.Context, *CreateRevisionRunRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRevisionRun not implemented")
}
func (UnimplementedSweatShopApplicationServiceServer) mustEmbedUnimplementedSweatShopApplicationServiceServer() {
}

// UnsafeSweatShopApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SweatShopApplicationServiceServer will
// result in compilation errors.
type UnsafeSweatShopApplicationServiceServer interface {
	mustEmbedUnimplementedSweatShopApplicationServiceServer()
}

func RegisterSweatShopApplicationServiceServer(s grpc.ServiceRegistrar, srv SweatShopApplicationServiceServer) {
	s.RegisterService(&SweatShopApplicationService_ServiceDesc, srv)
}

func _SweatShopApplicationService_CreateRevisionRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRevisionRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweatShopApplicationServiceServer).CreateRevisionRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/revisionrun.SweatShopApplicationService/CreateRevisionRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweatShopApplicationServiceServer).CreateRevisionRun(ctx, req.(*CreateRevisionRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SweatShopApplicationService_ServiceDesc is the grpc.ServiceDesc for SweatShopApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SweatShopApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revisionrun.SweatShopApplicationService",
	HandlerType: (*SweatShopApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRevisionRun",
			Handler:    _SweatShopApplicationService_CreateRevisionRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "revisionrun/service.proto",
}
