// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: revisionrun/service.proto

package stageTime_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StageTimeApplicationService_CreateRevisionRun_FullMethodName = "/revisionrun.StageTimeApplicationService/CreateRevisionRun"
)

// StageTimeApplicationServiceClient is the client API for StageTimeApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StageTimeApplicationServiceClient interface {
	CreateRevisionRun(ctx context.Context, in *CreateRevisionRunRequest, opts ...grpc.CallOption) (*Response, error)
}

type stageTimeApplicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStageTimeApplicationServiceClient(cc grpc.ClientConnInterface) StageTimeApplicationServiceClient {
	return &stageTimeApplicationServiceClient{cc}
}

func (c *stageTimeApplicationServiceClient) CreateRevisionRun(ctx context.Context, in *CreateRevisionRunRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, StageTimeApplicationService_CreateRevisionRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StageTimeApplicationServiceServer is the server API for StageTimeApplicationService service.
// All implementations must embed UnimplementedStageTimeApplicationServiceServer
// for forward compatibility
type StageTimeApplicationServiceServer interface {
	CreateRevisionRun(context.Context, *CreateRevisionRunRequest) (*Response, error)
	mustEmbedUnimplementedStageTimeApplicationServiceServer()
}

// UnimplementedStageTimeApplicationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStageTimeApplicationServiceServer struct {
}

func (UnimplementedStageTimeApplicationServiceServer) CreateRevisionRun(context.Context, *CreateRevisionRunRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRevisionRun not implemented")
}
func (UnimplementedStageTimeApplicationServiceServer) mustEmbedUnimplementedStageTimeApplicationServiceServer() {
}

// UnsafeStageTimeApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StageTimeApplicationServiceServer will
// result in compilation errors.
type UnsafeStageTimeApplicationServiceServer interface {
	mustEmbedUnimplementedStageTimeApplicationServiceServer()
}

func RegisterStageTimeApplicationServiceServer(s grpc.ServiceRegistrar, srv StageTimeApplicationServiceServer) {
	s.RegisterService(&StageTimeApplicationService_ServiceDesc, srv)
}

func _StageTimeApplicationService_CreateRevisionRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRevisionRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StageTimeApplicationServiceServer).CreateRevisionRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StageTimeApplicationService_CreateRevisionRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StageTimeApplicationServiceServer).CreateRevisionRun(ctx, req.(*CreateRevisionRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StageTimeApplicationService_ServiceDesc is the grpc.ServiceDesc for StageTimeApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StageTimeApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revisionrun.StageTimeApplicationService",
	HandlerType: (*StageTimeApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRevisionRun",
			Handler:    _StageTimeApplicationService_CreateRevisionRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "revisionrun/service.proto",
}
