// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: revisionrun/service.proto

package sweatShop_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// YachtApplicationServiceClient is the client API for YachtApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YachtApplicationServiceClient interface {
	CreateRevisionRun(ctx context.Context, in *CreateRevisionRunRequest, opts ...grpc.CallOption) (*Response, error)
}

type yachtApplicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYachtApplicationServiceClient(cc grpc.ClientConnInterface) YachtApplicationServiceClient {
	return &yachtApplicationServiceClient{cc}
}

func (c *yachtApplicationServiceClient) CreateRevisionRun(ctx context.Context, in *CreateRevisionRunRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/revisionrun.YachtApplicationService/CreateRevisionRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YachtApplicationServiceServer is the server API for YachtApplicationService service.
// All implementations must embed UnimplementedYachtApplicationServiceServer
// for forward compatibility
type YachtApplicationServiceServer interface {
	CreateRevisionRun(context.Context, *CreateRevisionRunRequest) (*Response, error)
	mustEmbedUnimplementedYachtApplicationServiceServer()
}

// UnimplementedYachtApplicationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedYachtApplicationServiceServer struct {
}

func (UnimplementedYachtApplicationServiceServer) CreateRevisionRun(context.Context, *CreateRevisionRunRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRevisionRun not implemented")
}
func (UnimplementedYachtApplicationServiceServer) mustEmbedUnimplementedYachtApplicationServiceServer() {
}

// UnsafeYachtApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YachtApplicationServiceServer will
// result in compilation errors.
type UnsafeYachtApplicationServiceServer interface {
	mustEmbedUnimplementedYachtApplicationServiceServer()
}

func RegisterYachtApplicationServiceServer(s grpc.ServiceRegistrar, srv YachtApplicationServiceServer) {
	s.RegisterService(&YachtApplicationService_ServiceDesc, srv)
}

func _YachtApplicationService_CreateRevisionRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRevisionRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YachtApplicationServiceServer).CreateRevisionRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/revisionrun.YachtApplicationService/CreateRevisionRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YachtApplicationServiceServer).CreateRevisionRun(ctx, req.(*CreateRevisionRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YachtApplicationService_ServiceDesc is the grpc.ServiceDesc for YachtApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YachtApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revisionrun.YachtApplicationService",
	HandlerType: (*YachtApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRevisionRun",
			Handler:    _YachtApplicationService_CreateRevisionRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "revisionrun/service.proto",
}
