// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: revisionrun/status.proto

package stageTime_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Statuses_GetStatus_FullMethodName = "/revisionrun.Statuses/GetStatus"
)

// StatusesClient is the client API for Statuses service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusesClient interface {
	GetStatus(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetReply, error)
}

type statusesClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusesClient(cc grpc.ClientConnInterface) StatusesClient {
	return &statusesClient{cc}
}

func (c *statusesClient) GetStatus(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetReply, error) {
	out := new(StatusGetReply)
	err := c.cc.Invoke(ctx, Statuses_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusesServer is the server API for Statuses service.
// All implementations must embed UnimplementedStatusesServer
// for forward compatibility
type StatusesServer interface {
	GetStatus(context.Context, *StatusGetRequest) (*StatusGetReply, error)
	mustEmbedUnimplementedStatusesServer()
}

// UnimplementedStatusesServer must be embedded to have forward compatible implementations.
type UnimplementedStatusesServer struct {
}

func (UnimplementedStatusesServer) GetStatus(context.Context, *StatusGetRequest) (*StatusGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedStatusesServer) mustEmbedUnimplementedStatusesServer() {}

// UnsafeStatusesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusesServer will
// result in compilation errors.
type UnsafeStatusesServer interface {
	mustEmbedUnimplementedStatusesServer()
}

func RegisterStatusesServer(s grpc.ServiceRegistrar, srv StatusesServer) {
	s.RegisterService(&Statuses_ServiceDesc, srv)
}

func _Statuses_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusesServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statuses_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusesServer).GetStatus(ctx, req.(*StatusGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Statuses_ServiceDesc is the grpc.ServiceDesc for Statuses service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Statuses_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revisionrun.Statuses",
	HandlerType: (*StatusesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Statuses_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "revisionrun/status.proto",
}
