apiVersion: v1
kind: ServiceAccount
metadata:
  name: yacht-application-server
  namespace: yacht
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: yacht
  name: yacht-application-server
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yacht-application-server
  namespace: yacht
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yacht-application-server
subjects:
- kind: ServiceAccount
  name: yacht-application-server
  namespace: yacht
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-all-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-all-namespaces-yas
subjects:
- kind: ServiceAccount
  name: yacht-application-server
  namespace: yacht
roleRef:
  kind: ClusterRole
  name: list-all-namespaces
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelines-controller-cluster-access-yas
subjects:
- kind: ServiceAccount
  name: yacht-application-server
  namespace: yacht
roleRef:
  kind: ClusterRole
  name: tekton-pipelines-controller-cluster-access
  apiGroup: rbac.authorization.k8s.io