apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yacht-application-server-deployment
  namespace: argocd
spec:
  project: app
  destination:
    name: dev11
    namespace: yacht
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: yacht-application-server
    targetRevision: 0.3.10
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            configmaps:
              yas-configuration:
                PIPELINE_WORKSPACE: yacht-tekton
            ingress:
              yacht-application-server:
                hostname: yas
                clusterName: dev11
                domain: 4sthings.tiab.ssc.sva.de
                tls:
                  host: yas.dev11.4sthings.tiab.ssc.sva.de
            customresources:
              yas-ingress-certificate:
                spec:
                  commonName: yas.dev11.4sthings.tiab.ssc.sva.de
                  dnsNames:
                  - yas.dev11.4sthings.tiab.ssc.sva.de
                  issuerRef:
                    name: cluster-issuer-approle
            secrets:
              redis-connection:
                secretKVs:
                  REDIS_SERVER: cmVkaXMtZGVwbG95bWVudC1oZWFkbGVzcy55YWNodC5zdmMuY2x1c3Rlci5sb2NhbA==
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
