---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: app
  destination:
    name: dev8
    namespace: yacht
    #server: 'https://10.100.136.78:6443'
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: yacht-tekton-resources
    targetRevision: v0.47.3
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            defaultNamespace: yacht
            enableTasks: true
            enablePipelines: true

            enableWorkspaces: true
            workspaces:
            yacht-kaniko-workspace:
              volumeMode: Filesystem
              storageClassName: nfs4-csi
              storage: 5Gi
              accessModes:
                - ReadWriteOnce

            enableGitSecretsSSH: true
            gitSecretsSSH:
              codehub:
                name: codehub-ssh
                labels:
                  app: yacht-tekton
                dataType: data
                secretKVs:
                  id_rsa: <path:apps/data/yacht#codehub-ssh>

            # enableSecrets: true
            # secrets:
            #   gitlab-pipeline-token3:
            #     name: gitlab-pipeline-token3
            #     labels:
            #       app: sthings-tekton
            #     secretKVs:
            #       token: <path:apps/data/yacht#redis-password>

            enableRegistryCredentials: true
            registryCredentials:
              scr-labda:
                labels:
                  app: yacht-teton
                dockerConfigJson: <path:apps/data/yacht#scr-labda>

            enableGitSecretsBasicAuth: false
            gitSecretsBasicAuth:
              codehub-basicauth:
                labels:
                  app: sthings-tekton
                namespace: tekton-cicd
                hostname: codehub.sva.de
                username: <path:apps/data/codehub#git_token_usernamee>
                password: <path:apps/data/codehub#git_token_password>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true