---
apiVersion: v2
name: yacht-application-server
description: A Helm chart for Kubernetes
type: application
version: 0.3.2
appVersion: "0.3.2"

dependencies:
- name: sthings-helm-toolkit
  version: 2.4.8
  repository: oci://eu.gcr.io/stuttgart-things
