---
namespace: yacht

configmaps:
  yas-configuration:
    PIPELINE_WORKSPACE: yacht-tekton

secrets:
  redis-connection:
    name: redis-connection
    labels:
      app: yacht-application-server
    dataType: data
    secretKVs:
      REDIS_SERVER: MTAuMzEuMTAxLjEzOA==
      REDIS_PORT: NjM3OQ==
      REDIS_PASSWORD: QXRsYW43aXM=
      REDIS_QUEUE: cmVkaXNxdWV1ZTp5YWNodC1yZXZpc2lvbnJ1bnM=

services:
  yacht-application-server:
    labels:
      app: yacht-application-server
    ports:
      - name: yas-port
        protocol: TCP
        value: 50051
        expose:
          service:
            type: ClusterIP
            port: 80
    selectorLabels:
      app: yacht-application-server
