namespace: yacht
configmaps:
  yas-configuration:
    PIPELINE_WORKSPACE: yacht-tekton
deployment:
  name: yacht-application-server
  labels:
    app: yacht-application-server
  selectorLabels:
    app: yacht-application-server
  ports:
    app-port:
      containerPort: 50051
      protocol: TCP
  allowPrivilegeEscalation: "false"
  privileged: "false"
  runAsNonRoot: "false"
  readOnlyRootFilesystem: "true"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  containers:
    yacht-application-server:
      image: eu.gcr.io/stuttgart-things/yacht-application-server
      replicaCount: 1
      imagePullPolicy: Always
      tag: 23.0507.1911-0.3.5
      securityContext: {}
secrets:
  redis-connection:
    name: redis-connection
    labels:
      app: yacht-application-server
    dataType: data
    secretKVs:
      REDIS_SERVER: MTAuMzEuMTAxLjEzOA==
      REDIS_PORT: NjM3OQ==
      REDIS_PASSWORD: QXRsYW43aXM=
      REDIS_QUEUE: cmVkaXNxdWV1ZTp5YWNodC1yZXZpc2lvbnJ1bnM=
services:
  yacht-application-server:
    labels:
      app: yacht-application-server
    ports:
      - name: yas-port
        protocol: TCP
        value: 50051
        expose:
          service:
            type: ClusterIP
            port: 80
    selectorLabels:
      app: yacht-application-server
customresources:
  yas-ingress-certificate:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: yacht-application-server-ingress
      labels:
        app: yacht-application-server
    spec:
      commonName: yas.app.sthings.tiab.ssc.sva.de
      dnsNames:
        - yas.app.sthings.tiab.ssc.sva.de
      issuerRef:
        name: cluster-issuer-ssc #cluster-issuer-approle
        kind: ClusterIssuer
      secretName: yacht-application-server-ingress-tls
ingress:
  yacht-application-server:
    labels:
      app: yacht-application-server
    name: yacht-application-server
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    service:
      name: yacht-application-server-service
      port: 80
      path: /
      pathType: Prefix
    hostname: yas
    clusterName: dev
    domain: app.sthings.tiab.ssc.sva.de
    tls:
      secretName: yacht-application-server-ingress-tls
      host: yas.app.sthings.tiab.ssc.sva.de
# RBAC
serviceAccounts:
  yacht-application-server:
    labels:
      app: yacht-application-server
roles:
  yacht-application-server:
    labels:
      app: yacht-application-server
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
          - watch
          - create
roleBindings:
  yacht-application-server:
    labels:
      app: yacht-application-server
    roleRef:
      kind: Role
      name: yacht-application-server
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: yacht-application-server
        namespace: yacht
clusterRoles:
  list-all-namespaces:
    labels:
      app: yacht-application-server
    rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
        verbs:
          - get
          - list
clusterRoleBindings:
  list-all-namespaces-yas:
    roleRef:
      kind: ClusterRole
      name: list-all-namespaces
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: yacht-application-server
        namespace: yacht
