---
name: Validate-Manifests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:
  validate-golang:
    name: Valdiate Manifests
    uses: stuttgart-things/stuttgart-things/.github/workflows/scan-polaris.yaml@main
    with:
      environment-name: k8s
      runs-on: arc-runner-scale-set-stagetime-server
      polaris-image: eu.gcr.io/stuttgart-things/sthings-polaris:8.5.4
      severity: danger
      #scan-object: manifest
      scan-object: helm
      scan-path: helm/stagetime-server
